name: gamenet_manager
description: GameNetManager

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bitsdojo_window: ^0.1.5
  cupertino_icons: ^1.0.5
  date_format: ^2.0.7
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_libserialport: ^0.3.0
  flutter_linear_datepicker: ^2.0.4
  flutter_screenutil: ^5.5.4
  get: ^4.6.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  path_provider: ^2.0.11
  shamsi_date: ^1.0.1
  win32: ^3.0.0

dev_dependencies:
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  json_serializable: ^6.5.0
  rounded_loading_button: ^2.1.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
